// <auto-generated />
namespace PortalRoemmers.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cambiando_tipo_string_a_byte_ModelSolicitudRRHH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambiando_tipo_string_a_byte_ModelSolicitudRRHH));
        
        string IMigrationMetadata.Id
        {
            get { return "202306071448376_Cambiando_tipo_string_a_byte_ModelSolicitudRRHH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
